name: CI

on:
  push:
    branches:
    - latest
  schedule:
  - cron: "0 0 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
          fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install Python dependencies
      run: pip install -r requirements.txt
    - name: Build documentation and deploy
      run: ./.github/workflows/build_helper.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        QUARTZY_USERNAME: ${{ secrets.QUARTZY_USERNAME }}
        QUARTZY_PASSWORD: ${{ secrets.QUARTZY_PASSWORD }}
